# Generated by Django 5.1.11 on 2025-08-27 22:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': False, 'template': 'components/streamfield/blocks/heading2_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'code', 'blockquote', 'hr']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "If left blank, the image's global alt text will be used.", 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('image_alt_text', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 6)]], {})}),
        ),
    ]
